import json
import os

import joblib
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt


st.set_page_config(page_title="CampusPulse Dashboard", layout="wide")

st.title("CampusPulse — Student Performance Dashboard")

DATA_PATH = os.path.join("data", "processed_student_data.csv")
MODEL_PATH = os.path.join("models", "performance_model.pkl")
META_PATH = os.path.join("models", "metadata.json")


@st.cache_data
def load_data():
    if not os.path.exists(DATA_PATH):
        st.error("Processed data not found. Run `python app/analysis.py` first.")
        return None
    return pd.read_csv(DATA_PATH)


@st.cache_data
def load_model():
    if not os.path.exists(MODEL_PATH):
        st.error("Trained model not found. Run `python app/analysis.py` first.")
        return None
    return joblib.load(MODEL_PATH)


@st.cache_data
def load_metadata():
    if not os.path.exists(META_PATH):
        return {}
    with open(META_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


df = load_data()
if df is None:
    st.stop()

model = load_model()
metadata = load_metadata()

with st.sidebar:
    st.header("Settings")
    show_preview = st.checkbox("Show dataset preview", value=True)
    # compute safe slider bounds (number of features excludes Student_ID and Final_GPA)
    max_features = max(1, df.shape[1] - 2)
    default_n = min(3, max_features)
    top_n = st.slider("Top N features to show", 1, max_features, default_n)

if show_preview:
    st.subheader("Dataset preview")
    st.dataframe(df.head(100))

st.subheader("Model metrics")
r2 = metadata.get("r2")
if r2 is not None:
    st.metric("R2 Score", f"{r2:.3f}")
else:
    st.info("R2 score not available in metadata.")

if model is not None and hasattr(model, "feature_importances_"):
    st.subheader("Feature importances")
    fi = metadata.get("feature_importances")
    if fi:
        fi_series = pd.Series(fi).sort_values(ascending=False).head(top_n)
        fig, ax = plt.subplots()
        fi_series.plot.bar(ax=ax)
        st.pyplot(fig)
    else:
        st.info("No feature importance metadata available.")

st.subheader("Predictions sample")
if model is not None:
    # show a small sample with predictions (use first 50 rows)
    X = df.drop(["Student_ID", "Final_GPA"], axis=1)
    sample = df.head(50).copy()
    try:
        sample["Predicted_GPA"] = model.predict(X.head(50))
        st.dataframe(sample[["Student_ID", "Final_GPA", "Predicted_GPA"]])
        fig2, ax2 = plt.subplots()
        ax2.scatter(sample["Final_GPA"], sample["Predicted_GPA"], alpha=0.7)
        ax2.plot([sample["Final_GPA"].min(), sample["Final_GPA"].max()], [sample["Final_GPA"].min(), sample["Final_GPA"].max()], color="red", linestyle="--")
        ax2.set_xlabel("Actual GPA")
        ax2.set_ylabel("Predicted GPA")
        st.pyplot(fig2)
    except Exception as e:
        st.error(f"Could not compute predictions: {e}")

st.markdown("---")
st.write("Generated by CampusPulse analytics pipeline")
